// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Guy Heckman. Licensed under the GNU Affero General Public License v3.0 or later (see LICENSE).
// SnugCut app: the English text of every message app.js shows (#128). Whole sentences only, never pieced together:
// {name} is a value; {n, plural, one {# part} other {# parts}} picks by Intl.PluralRules (# is the number, =0 an exact
// match) and {v, select, in {…} other {…}} by value. The page's own text stays in app/index.html, marked with data-t
// keys. "lib.*" words the library's messages (README "Library messages"). tools/build.py fails on a key that is used
// but missing, or defined but unused.
export const EN = {
  "fatal.noClipper": "The geometry library didn't load, so shapes can't be nested. Reload the page to try again.",
  "status.noEngine": "Geometry engine unavailable",
  "len.plateW": "Plate width",
  "len.plateH": "Plate height",
  "len.kerf": "Kerf",
  "len.gap": "Extra gap",
  "len.margin": "Edge margin",
  "field.nan": "Enter a number; still using {value} {unit}.",
  "field.notPositive": "{field} must be more than 0; still using {value} {unit}.",
  "field.negative": "{field} can't be negative; still using {value} {unit}.",
  "kerf.placeholder": "e.g. {value}",
  "kcalc.nan": "Enter a number.",
  "kcalc.designedPositive": "Designed must be more than 0.",
  "kcalc.measuredPositive": "Measured must be more than 0.",
  "kcalc.measuredSmaller": "Measured must be smaller than designed: the cut takes material away.",
  "kcalc.none": "Kerf: –",
  "kcalc.result": "Kerf: {value} {unit}",
  "toast.kerfUpdated": "Kerf updated",
  "toast.saved": "Saved {file}",
  "status.nesting": "Nesting…",
  "status.searching": "Searching… {elapsed} of {total} s · {tried} layouts tried",
  "status.best": "Best of {tried} layouts tried.",
  "status.ready": "Ready.",
  "status.longer": "A longer search may save a plate.",
  "run.stale": "Stopped before a new layout was ready. The plates shown are out of date.",
  "run.noArea": "The edge margin leaves no usable area on the plate.",
  "run.finished": "Nesting finished: {n, plural, one {# plate} other {# plates}}, {fill} average utilization, {placed} of {want} parts placed.",
  "run.nothingPlaced": "Nesting finished: nothing could be placed.",
  "run.noParts": "No parts to nest.",
  "run.efficiency": "Efficiency {rating} out of 10: the parts use {eff} of the material the job takes up.",
  "run.oversize": "{n, plural, one {# file doesn't fit on the plate and was left out.} other {# files don't fit on the plate and were left out.}}",
  "notice.nestError": "Nesting stopped after an error: {error}",
  "notice.dismiss": "Dismiss",
  "notice.dismissLabel": "Dismiss: {text}",
  "part.size": "{w} × {h} {unit}",
  "part.sizeTooBig": "{w} × {h} {unit} · too big",
  "part.drawnIn": "Drawn in",
  "part.inches": "inches",
  "part.qty": "Qty",
  "part.qtyErr": "Enter a whole number, 0 or more; still using {qty}.",
  "part.holesTitle": "Nest other parts inside this part's holes (only if every closed inner outline is cut, not scored)",
  "part.holesLabel": "Nest parts inside the holes of {name}",
  "part.noHoles": "No holes to nest parts in",
  "part.lockTitle": "Lock orientation (no rotation)",
  "part.lockLabel": "Lock orientation of {name}",
  "part.removeTitle": "Remove",
  "part.removeLabel": "Remove {name}",
  "part.readIn": "{name} read in {units, select, in {inches} other {millimeters}}: {w} × {h} {unit}.",
  "parts.none": "No parts yet. Add SVG or DXF files above.",
  "parts.count": "{files, plural, one {# file} other {# files}} · {n, plural, one {# part} other {# parts}}",
  "files.only": "Only .svg and .dxf files can be added.",
  "files.precomp": "{name} was downloaded from SnugCut with kerf compensation built in, so it won't be compensated again.",
  "files.hiddenItem": "{n} from {name}",
  "files.hidden": "Left out hidden shapes (not shown, so not cut): {list}.",
  "files.stripped": "Removed links to outside files (web images, fonts or styles) and markup that isn't SVG from {list}; only what's inside the file is used.",
  "stat.eff": "{rating} out of 10",
  "stat.effLabel": "Efficiency · {eff}",
  "stat.effNone": "Efficiency",
  "layout.oversize": "{name} ({w} × {h} {unit}) doesn't fit inside the plate's margins. It was left out.",
  "layout.oversizeBbox": "{name} ({w} × {h} {unit}) doesn't fit inside the plate's margins in either orientation. It was left out.",
  "layout.oversizeRot": "{name} ({w} × {h} {unit}) doesn't fit inside the plate's margins at any allowed rotation. It was left out.",
  "layout.addFiles": "Add SVG or DXF files to see them nested on plates.",
  "layout.setQty": "Set a quantity above zero to place parts.",
  "layout.nonePlaced": "No parts could be placed.",
  "plate.rotated": "{name} (rotated {ang}°)",
  "plate.alt": "Plate {i} of {n}: {parts, plural, one {# part} other {# parts}}, {fill} utilization",
  "plate.line": "{name} × {n}",
  "plate.lineRot": "{name} × {n} ({rots})",
  "plate.rot": "{n} rotated {ang}°",
  "plate.title": "Plate {i} of {n}",
  "plate.meta": "{parts, plural, one {# part} other {# parts}} · {fill} utilization · {w} × {h} {unit}",
  "plate.metaOffcut": "{parts, plural, one {# part} other {# parts}} · {fill} utilization · {w} × {h} {unit} · offcut {cw} × {ch} {unit}",
  "plate.download": "Download {format}",
  "plate.downloadLabel": "Download {format}, plate {i} of {n}",
  "plate.list": "Parts on this plate",
  "plate.staleTitle": "Out of date: wait for the new layout",
  "plate.busyTitle": "Searching: stop the search, or use Download all, so every plate comes from the same layout",
  "export.compNote": "Kerf compensation is built in ({value} {unit} per side): don't add a kerf offset in your cutter's software.",
  "lib.dxf.binary": "{name} is a binary DXF. Save it as an ASCII DXF and try again.",
  "lib.dxf.unreadable": "{name} isn't a readable DXF file.",
  "lib.dxf.noUnits": "{name} doesn't say what units it's drawn in, so it was read as {units, select, in {inches, as its imperial measurement setting suggests} other {millimeters}}. If that's wrong, change it next to the part in the parts list.",
  "lib.dxf.tooManyItems": "{name} expands to more than {limit} items (blocks and arrays), so it wasn't added.",
  "lib.dxf.tooManyPoints": "{name} draws more than {limit} points (blocks and arrays repeat them), so it wasn't added.",
  "lib.dxf.splineDegree": "{name} has a spline of degree {degree}, but only degrees 1 to 11 can be read, so it wasn't added.",
  "lib.dxf.hiddenLeftOut": "{name}: left out {count, plural, one {# item} other {# items}} on frozen, off, non-plotting or Defpoints layers.",
  "lib.dxf.skipped": "{name}: skipped {list} (only lines, arcs, circles, ellipses, polylines and splines are cut).",
  "lib.dxf.nothingToCut": "{name} has no lines, arcs, circles, ellipses, polylines or splines to cut on visible layers in model space{hidden, plural, =0 {.} one {; # item is on frozen, off, non-plotting or Defpoints layers.} other {; # items are on frozen, off, non-plotting or Defpoints layers.}}",
  "lib.svg.unreadable": "{name} isn't a readable SVG file.",
  "lib.svg.tooManyCopies": "{name} repeats shapes through linked copies (<use>) more than {limit} times, so it wasn't added.",
  "lib.svg.nothingVisible": "{name} has no visible shapes to place.",
  "lib.svg.nothingToCut": "{name} has no cuttable shapes.",
  "lib.svg.noClosedOutline": "{name} has no closed outline to nest.",
  "lib.kerf.holeTooNarrow": "A hole in {name} is narrower than the kerf, so it was left as drawn.",
  "lib.kerf.markup": "{name} has text, images, linked copies or effects, so its kerf can't be compensated; it is exported as drawn.",
  "lib.dxfOut.nothing": "{name} has nothing that can be written to DXF.",
  "lib.dxfOut.clipping": "Not in the DXF: clipping, masks and filters (shapes exported whole) in {name}.",
  "lib.dxfOut.text": "Not in the DXF: text in {name}.",
  "lib.dxfOut.images": "Not in the DXF: images in {name}.",
  "lib.dxfOut.use": "Not in the DXF: linked copies (<use>) in {name}.",
  "lib.dxfOut.element": "Not in the DXF: <{tag}> elements in {name}.",
  "lib.dxfOut.paint": "Not in the DXF: gradient and pattern colors (exported black) in {name}.",
  "lib.dxfOut.unreadable": "Not in the DXF: unreadable paths in {name}.",
  "lib.dxfOut.fills": "Filled areas are written as their outlines.",
};
