#!/usr/bin/env python3
"""Generate snugcut.html (one self-contained file) from app/ and lib/.

    python3 tools/build.py          write snugcut.html
    python3 tools/build.py --check  exit 1 if snugcut.html is out of date

app/index.html, app/snugcut.css, app/app.js and lib/snugcut.js are the source of truth. The page's stylesheet link
and module script are replaced by the CSS and the JavaScript inline: the library first, then the app, in one
classic script (export/import lines removed). In the CSP, script-src allows that one inline script by its sha256 hash
(no 'unsafe-inline', so injected inline handlers can't run), and 'self' is dropped since nothing is loaded from disk.
Python 3 standard library only.
"""
import base64, hashlib, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "snugcut.html"
NOTICE = "<!-- Generated by tools/build.py from app/ and lib/: edit those files, not this one. -->"

def read(rel):
    return (ROOT / rel).read_text(encoding="utf-8")

def fail(msg):
    sys.exit(f"build.py: {msg}")

def module_body(src, rel):
    src = re.sub(r"^import\s*\{[^}]*\}\s*from\s*\"[^\"]+\";\n", "", src, flags=re.M)   # app: the library import
    src = re.sub(r"^export (?=(?:async function|function|const|let|class) )", "", src, flags=re.M)
    src = re.sub(r"^export \{[^}]*\};\n", "", src, flags=re.M)
    left = re.findall(r"^(?:import|export)\b.*", src, flags=re.M)
    if left: fail(f"{rel}: unsupported import/export form: {left[0][:80]}")
    if re.search(r"</script", src, flags=re.I): fail(f"{rel} contains '</script', which would end the inline script")
    return src

def build():
    html, css = read("app/index.html"), read("app/snugcut.css")
    lib, app = module_body(read("lib/snugcut.js"), "lib/snugcut.js"), module_body(read("app/app.js"), "app/app.js")
    link = '<link rel="stylesheet" href="snugcut.css">\n'
    mod = '<script type="module" src="app.js"></script>\n'
    if html.count(link) != 1 or html.count(mod) != 1: fail("app/index.html must have exactly one snugcut.css link and one app.js module script")
    csp = re.search(r'(<meta http-equiv="Content-Security-Policy" content=")([^"]*)(">)', html)
    if not csp: fail("app/index.html has no Content-Security-Policy <meta>")
    script = "\n(() => {\n" + lib + app + "})();\n"
    digest = "'sha256-" + base64.b64encode(hashlib.sha256(script.encode("utf-8")).digest()).decode() + "'"
    dirs = []
    for d in csp.group(2).split(";"):
        d = d.strip()
        if "'unsafe-inline'" in d and d.startswith("script-src"): fail("app/index.html: script-src must not allow 'unsafe-inline'")
        if d.startswith("script-src"): d = d.replace("'self'", digest)    # the one inline script, by hash
        else: d = d.replace("'self' ", "")
        dirs.append(d)
    html = html.replace(csp.group(0), csp.group(1) + "; ".join(dirs) + csp.group(3), 1)
    html = html.replace(link, "<style>\n" + css + "</style>\n", 1)
    html = html.replace(mod, "<script>" + script + "</script>\n", 1)
    if not html.startswith("<!doctype html>\n"): fail("app/index.html must start with <!doctype html>")
    return html.replace("<!doctype html>\n", "<!doctype html>\n" + NOTICE + "\n", 1)

if __name__ == "__main__":
    out = build()
    if "--check" in sys.argv[1:]:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != out:
            fail("snugcut.html is out of date: run python3 tools/build.py")
        print("snugcut.html is up to date")
    else:
        OUT.write_text(out, encoding="utf-8")
        print(f"wrote {OUT.relative_to(ROOT)} ({len(out.encode('utf-8'))} bytes)")
