#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Guy Heckman. Licensed under the GNU Affero General Public License v3.0 or later (see LICENSE).
"""Generate snugcut.html (one self-contained file) from app/ and lib/.

    python3 tools/build.py          write snugcut.html
    python3 tools/build.py --check  exit 1 if snugcut.html is out of date

app/index.html, app/snugcut.css, app/app.js, app/strings-en.js and lib/snugcut.js are the source of truth. The page's
stylesheet link and module script are replaced by the CSS and the JavaScript inline: the library first, then the
string table, then the app, in one strict classic script (export/import lines removed). In the CSP, script-src allows that one inline script by its sha256 hash
(no 'unsafe-inline', so injected inline handlers can't run), and 'self' is dropped since nothing is loaded from disk.
Both runs check that each library <script> URL is in the CSP's script-src (and clipper-lib's in connect-src) with
integrity and crossorigin (#387), and the string table (#128): a key app.js uses that isn't defined, a defined key nothing uses, a library
message code without its "lib." entry (or the reverse), or a data-t key in the page used twice, stops the build.
Python 3 standard library only.
"""
import base64, hashlib, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "snugcut.html"
NOTICE = "<!-- Generated by tools/build.py from app/ and lib/: edit those files, not this one. -->"

def read(rel):
    return (ROOT / rel).read_text(encoding="utf-8")

def fail(msg):
    sys.exit(f"build.py: {msg}")

def module_body(src, rel):
    src = re.sub(r"^import\s*\{[^}]*\}\s*from\s*\"[^\"]+\";\n", "", src, flags=re.M)   # app: the library import
    src = re.sub(r"^export (?=(?:async function|function|const|let|class) )", "", src, flags=re.M)
    src = re.sub(r"^export \{[^}]*\};\n", "", src, flags=re.M)
    left = re.findall(r"^(?:import|export)\b.*", src, flags=re.M)
    if left: fail(f"{rel}: unsupported import/export form: {left[0][:80]}")
    if re.search(r"</script", src, flags=re.I): fail(f"{rel} contains '</script', which would end the inline script")
    return src

def check_text(html, strings, app, lib):
    defined = re.findall(r'^\s*"([\w.]+)":', strings, flags=re.M)
    twice = sorted({k for k in defined if defined.count(k) > 1})
    if twice: fail(f"app/strings-en.js defines {', '.join(twice)} more than once")
    block = re.search(r"^export const MESSAGES = \{\n(.*?)^\};", lib, flags=re.M | re.S)
    if not block: fail("lib/snugcut.js has no MESSAGES table")
    libkeys = {"lib." + c for c in re.findall(r'^\s*"([\w.]+)":', block.group(1), flags=re.M)}
    keys, prefixes = set(defined), {k.split(".")[0] for k in defined}
    # keys app.js names: t("key") calls, and any other "prefix.name" literal with a table prefix (picked at run time)
    named = {k for k in re.findall(r'\bt\(\s*"([\w.]+)"', app) if not k.endswith(".")} | {l for l in re.findall(r'"(\w+(?:\.\w+)+)"', app) if l.split(".")[0] in prefixes}
    missing = sorted((named | libkeys) - keys)
    if missing: fail(f"app/strings-en.js has no text for {', '.join(missing)}")
    unused = sorted(keys - named - libkeys)
    if unused: fail(f"app/strings-en.js defines {', '.join(unused)}, which nothing uses")
    page = re.findall(r'\sdata-t(?:-[\w-]+)?="([^"]*)"', html)
    twice = sorted({k for k in page if page.count(k) > 1})
    if twice: fail(f"app/index.html uses the data-t key {', '.join(twice)} more than once")

def check_libs(html, csp):
    # every external script is allowed by script-src and pinned with integrity + crossorigin, and clipper-lib's URL is
    # in connect-src too, where the search worker fetches it (#387): a library bump that misses one URL stops the build
    dirs = {d.split()[0]: d.split()[1:] for d in (x.strip() for x in csp.split(";")) if d}
    tags = re.findall(r"<script\b[^>]*\ssrc=\"https?://[^>]*>", html)
    if not tags: fail("app/index.html has no library <script> tags")
    for tag in tags:
        src = re.search(r'\ssrc="([^"]+)"', tag).group(1)
        if src not in dirs.get("script-src", []): fail(f"app/index.html: {src} is not in the CSP's script-src")
        if not re.search(r'\sintegrity="sha(256|384|512)-[^"]+"', tag) or 'crossorigin="anonymous"' not in tag:
            fail(f"app/index.html: the <script> for {src} needs integrity and crossorigin=\"anonymous\"")
    clip = re.search(r'<script\b[^>]*\sid="clipper-lib"[^>]*\ssrc="([^"]+)"', html)
    if not clip: fail('app/index.html has no <script id="clipper-lib">')
    if clip.group(1) not in dirs.get("connect-src", []): fail(f"app/index.html: {clip.group(1)} is not in the CSP's connect-src (the search worker fetches it)")

def build():
    html, css = read("app/index.html"), read("app/snugcut.css")
    check_text(html, read("app/strings-en.js"), read("app/app.js"), read("lib/snugcut.js"))
    lib, app = module_body(read("lib/snugcut.js"), "lib/snugcut.js"), module_body(read("app/app.js"), "app/app.js")
    lib += module_body(read("app/strings-en.js"), "app/strings-en.js")
    link = '<link rel="stylesheet" href="snugcut.css">\n'
    mod = '<script type="module" src="app.js"></script>\n'
    if html.count(link) != 1 or html.count(mod) != 1: fail("app/index.html must have exactly one snugcut.css link and one app.js module script")
    csp = re.search(r'(<meta http-equiv="Content-Security-Policy" content=")([^"]*)(">)', html)
    if not csp: fail("app/index.html has no Content-Security-Policy <meta>")
    check_libs(html, csp.group(2))
    # strict, as app/ is as ES modules, so testing app/ covers the shipped file (#289)
    script = "\n(() => {\n\"use strict\";\n" + lib + app + "})();\n"
    digest = "'sha256-" + base64.b64encode(hashlib.sha256(script.encode("utf-8")).digest()).decode() + "'"
    dirs = []
    for d in csp.group(2).split(";"):
        d = d.strip()
        if "'unsafe-inline'" in d and d.startswith("script-src"): fail("app/index.html: script-src must not allow 'unsafe-inline'")
        if d.startswith("script-src"): d = d.replace("'self'", digest)    # the one inline script, by hash
        else: d = " ".join(w for w in d.split() if w != "'self'")   # wherever it stands in the directive (#296)
        dirs.append(d)
    html = html.replace(csp.group(0), csp.group(1) + "; ".join(dirs) + csp.group(3), 1)
    html = html.replace(link, "<style>\n" + css + "</style>\n", 1)
    html = html.replace(mod, "<script>" + script + "</script>\n", 1)
    if not html.startswith("<!doctype html>\n"): fail("app/index.html must start with <!doctype html>")
    return html.replace("<!doctype html>\n", "<!doctype html>\n" + NOTICE + "\n", 1)

if __name__ == "__main__":
    out = build()
    if "--check" in sys.argv[1:]:
        # compared as bytes and written with \n on every platform, so a Windows build can't turn every line into \r\n
        # unseen (#292)
        if not OUT.exists() or OUT.read_bytes() != out.encode("utf-8"):
            fail("snugcut.html is out of date: run python3 tools/build.py")
        print("snugcut.html is up to date")
    else:
        OUT.write_text(out, encoding="utf-8", newline="\n")
        print(f"wrote {OUT.relative_to(ROOT)} ({len(out.encode('utf-8'))} bytes)")
